import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Momentum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="max-w-[1684px] mx-auto">
          <Header />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
